services: '3.9'

services:
  app:
    build: .
    container_name: app_python
    command: python3 -u run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file: .env
  db:
    image: mongo:latest
    container_name: app_mongo
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
    env_file: .env